#:import get_color_from_hex kivy.utils.get_color_from_hex
WindowManager:
    Login:
    Inicio:
    Search:
    Musicas:
    Pesquisar:
    Playlist:
    Carregamento:




#: include kvfiles/musica_playlist.kv
#: include kvfiles/playlist.kv
#: include kvfiles/search.kv
#: include kvfiles/pesquisar.kv
#: include kvfiles/inicio.kv
#: include kvfiles/login.kv
#: include kvfiles/carregamento.kv

